name: CustomBook
main: Teunboeke\CustomBook\Main
version: 1.0.0
api: [3.15.2]
author: Teunboeke
description: create custombooks that players can read
commands:
    book:
      description: "Get the specified book."
      usage: "/book <book>"
            
     books:
         description: "Get a list of books."
         usage: "/books"
             
